# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane
fastlane_require 'dotenv'
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end


  desc "Prepare and archive app"
  lane :prepare  do
      build_number = number_of_commits()
      Dir.chdir("../..") do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "appbundle","--release","--build-name=1.0.#{build_number}","--build-number=#{build_number}")
#         sh("flutter", "build", "apk","--release","--build-name=1.0.#{build_number}","--build-number=#{build_number}","--target-platform","android-arm,android-arm64","--split-per-abi")
      end
  end

    desc "Prepare and archive single apk app"
    lane :prepare_single_apk  do
        build_number = number_of_commits()
        Dir.chdir("../..") do
          sh("flutter", "packages", "get")
          sh("flutter", "clean")
          sh("flutter", "build", "apk","--release","--build-name=1.0.#{build_number}","--build-number=#{build_number}")
        end
    end

    desc "[Firebase-App-Distribute] Deploy a new version to the Firebase App-Distribute"
    lane :firebase_deploy do
      prepare_single_apk
      commit = last_git_commit
      firebase_app_distribution(
          app: "1:1059157132999:android:02a067b30029ec464fa0e2",
          apk_path: "../build/app/outputs/apk/release/app-release.apk",
          testers: "m.taweechai@gmail.com",
          release_notes: "Latest Android Instacalc Beta build : #{commit[:message]}",
          firebase_cli_path: "/usr/local/bin/firebase",
          groups: "default"
      )
    end

  desc "[Internal-Track] Deploy a new version to the Google Play"
  lane :internal_deploy do
    prepare
    supply(
          track: "internal",
          aab_paths: ["../build/app/outputs/bundle/release/app-release.aab"],
#           apk_paths: ["../build/app/outputs/apk/release/app-armeabi-v7a-release.apk","../build/app/outputs/apk/release/app-arm64-v8a-release.apk"],
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          rollout: "1.0"
        )
  end

  desc "[Alpha-Track] Deploy a new version to the Google Play"
  lane :alpha_deploy do
    prepare
    supply(
          track: "alpha",
#           apk_paths: ["../build/app/outputs/apk/release/app-armeabi-v7a-release.apk","../build/app/outputs/apk/release/app-arm64-v8a-release.apk"],
          aab_paths: ["../build/app/outputs/bundle/release/app-release.aab"],
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          rollout: "1.0"
        )
  end

    desc "[Alpha-Track] Deploy a new version to the Huawei"
    lane :huawei_deploy do
        Dotenv.overload '../.env'
      prepare_single_apk
#       huawei_appgallery_connect(
#             client_id: ENV['HUAWEI_STORE_ID'],
#             client_secret: ENV['HUAWEI_STORE_SECRET'],
#             app_id: "102778913", #app id
#             apk_path: "../build/app/outputs/apk/release/app-release.apk", #path to the apk/aab file
#             submit_for_review: true
#         )
    end
end
